---
blank_issues_enabled: false
contact_links:
  - name: MyAmazingProject Community Support
    url: https://github.com/MasteryEducation/MyAmazingProject/discussions
    about: Please ask and answer questions here.
